project_name: inria 
run_name: unet_resnet50_on_inria 
random_seed: 42

trainer_kwargs:
  max_epochs: 10
  #strategy: 'ddp'
  #devices: 4
  precision: '16-mixed' 
  num_sanity_val_steps: 0
  use_distributed_sampler: True

logger_kwargs:
  log_to_h5: False 
  log_to_csv: False 
  log_to_wandb: False 
  log_to_tensorboard: False
  wandb_init_kwargs:
    tags: ["inria", "resnet50"]
    notes: "testing building segmentation" 
  log_every_n_steps: 10 
  log_every_n_epochs: 1
  log_models: True 

# either provide a df, or specify the various samplers
dataset:
  name: Inria_Building_Segmentation_HDF5
  src: geovision.data.inria 
  kwargs:
    df: null 
    tabular_sampler:
      name: stratified_tabular_sampler
      src: geovision.data.samplers
      kwargs:
        val_frac: 0.15 
        test_frac: 0.15
        split_on: location 
    spatial_sampler: null
      # name: tiling
      # src: geovision.data.samplers
      # kwargs:
        # tile_size: 256 
        # tile_stride: 200 
    spectral_sampler: null
    temporal_sampler: null

    transforms: |
      from torch import float32
      from torchvision.transforms import v2 as T
      image_pre = T.Compose([
        T.ToImage(),
        T.ToDtype(float32, scale = True),
      ])
      target_pre = T.Compose([
        T.ToImage(),
        T.ToDtype(float32, scale = False),
      ])
      train_aug = T.Compose([
        T.RandomVerticalFlip(0.5),
        T.RandomHorizontalFlip(0.5),
      ])
      eval_aug = T.Identity()

    batch_transform:
      name: CutMix 
      src: torchvision.transforms.v2 
      kwargs:
        alpha: 0.4

  
dataloader_kwargs:
  # effective batch size = batch_size // gradient_accumulation
  batch_size: 64 
  gradient_accumulation: 1
  num_workers: 16 
  persistent_workers: False 
  pin_memory: True 
  prefetch_factor: 8 

module:
  name: ClassificationModule 
  src: geovision.models.interfaces
  kwargs:
    ckpt_path: null
    model_encoder:
      name: ResNet_Encoder
      src: geovision.models.resnet
      kwargs:
        layers: 50 
        residual_block_name: bottleneck 
        weights:
          name: ResNet50_Weights.FMOW_RGB_GASSL
          src: torchgeo 
          kwargs: null
        # torchvision, torchgeo, timm, path, url
        # weights_init: torchgeo 
        # weights_param: ResNet50_Weights.FMOW_RGB_GASSL

    model_decoder: 
      name: UNet_Decoder
      src: geovision.models.unet
      kwargs:
        upsampling: bilinear
        central_block: 
          name: ResidualBlock
          src: geovision.models.resnet
          kwargs:
            residual_path: basic 
            identity_path: identity 
        conv_block:
          name: ResidualBlock
          src: geovision.models.resnet
          kwargs:
            residual_path: basic 
            identity_path: identity
    
# used for validation
# for segmentation: mIoU, Dice, Pixel Accuracy
 # - name: name of the metric constructor / class
  # - src: name of the module / library 
  # - kwargs: dict of init kwargs for the class, defaults to none
  # - key: name to display on chart / legend, defaults to name

# confusion matrix is always tracked for classification

metrics:
  - name: JaccardIndex 
    src: torchmetrics 
    kwargs:
      sync_on_compute: True
    key: IoU 
 
criterion:
  name: CrossEntropyLoss
  src: torch.nn
  kwargs:
    reduction: mean

optimizer:
  name: SGD 
  src: torch.optim
  kwargs:
    lr: 5.0e-6
    momentum: 0.9
    weight_decay: 5.0e-4

schedulers:
  - name: LinearLR 
    src: torch.optim.lr_scheduler
    kwargs:
      start_factor: 0.001 
      end_factor: 0.9 
      total_iters: 200 

  - name: LinearLR 
    src: torch.optim.lr_scheduler
    kwargs:
      start_factor: 1.0 
      end_factor: 0.001 
      total_iters: 5

scheduler_milestones: [200]

scheduler_kwargs:
  interval: epoch 
  frequency: 3
  monitor: train_loss_epoch 
  
# warmup_scheduler: LinearLR 
# warmup_scheduler_kwargs:
  # start_factor: 0.001 
  # end_factor: 0.9 
  # total_iters: 200 
# warmup_steps: 200 

# scheduler_name: LinearLR 
# scheduler_kwargs:
  # start_factor: 1.0 
  # end_factor: 0.001 
  # total_iters: 5

# scheduler_config_kwargs:
  # interval: epoch 
  # frequency: 3
  # monitor: train_loss_epoch 